### ISSUE TITLE
Strange ngrok dependency

### ISSUE THREAD

**Issue by adrianlzt** [frangam/artdet#2]
Trying to run the app for the first time failed because ngrok was expecting an authtoken configured.

I find quite strange that this app tries to configure ngrok and exposes publicly my local instance by default. I would expect the app running in localhost and leave to my decision if I want to share it with Internet.

Also, I thin you should remove from the code your ngrok personal authtoken ([here](https://github.com/frangam/artdet/blob/main/src/run.py#L15)).

**Comment by frangam** [comment]
Thank you for pointing this out! You’re absolutely right —the app shouldn’t expose the local instance via ngrok by default without explicit consent. We’ve now modified the code so that ngrok only runs if the USE_NGROK=true environment variable is set, allowing the app to run locally by default.

Also, we’ve removed the ngrok authtoken from the code to avoid any security issues. I appreciate your feedback and attention to detail!

Please feel free to check the updated version, and let me know if you notice anything else.

Best regards!
